version: '3.8'

services:
  traderview-server:
    build:
      context: .
      dockerfile: traderview/traderview.Server/Dockerfile
    container_name: traderview-server
    ports:
      - "5000:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker
      - ASPNETCORE_URLS=http://+:8080
      - CORS_ALLOWED_ORIGINS=http://localhost:3000,http://localhost:5173
      - AllowedHosts=*
      
      # Database Configurations (Using Environment Variables)
      - ConnectionStrings__TradingDatabase=Server=host.docker.internal;Database=TradingBE;User Id=sa;Password=${SQL_PASSWORD};TrustServerCertificate=true;Encrypt=false;
      - Database__User=sa
      - Database__Password=${SQL_PASSWORD}
      - Database__Host=host.docker.internal
      - Database__DbName=TradingBE
      
      # IBKR API & Gateway Settings
      - IBKR__Token=${IBKR_TOKEN}
      - IBKR__QueryId=${IBKR_QUERY_ID}
      - IBKR__QueryTodayExecutionsId=${IBKR_TODAY_EXEC_ID}
      - IBKR__BaseUrl=https://ndcdyn.interactivebrokers.com/AccountManagement/FlexWebService/SendRequest
      - IBKR__OutputFilePath=/app/documents
      
      - IBKRClient__SocketUrl=host.docker.internal
      - IBKRClient__Port=4002
      - IBKRClient__ClientId=10000
      
      # Financial Modeling Prep API Settings
      - FinancialModelingPrep__ApiKey=${FMP_API_KEY}
      - FinancialModelingPrep__BaseUrl=https://financialmodelingprep.com/stable
      - FinancialModelingPrep__OutputFilePath=/app/documents
      
      # Logging Levels
      - Logging__LogLevel__Default=Information
      - Logging__LogLevel__Microsoft.AspNetCore=Warning

    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - traderview-doc-storage:/app/documents
    networks:
      - traderview-network

  traderview-client:
    build:
      context: .
      dockerfile: traderview/traderview.client/Dockerfile
    container_name: traderview-client
    ports:
      - "3000:80"
    depends_on:
      - traderview-server
    networks:
      - traderview-network

networks:
  traderview-network:
    driver: bridge

volumes:
  traderview-doc-storage:
    driver: local