namespace TraderView.Application.Features.TradeExecutions.Command.Update
{
    public class UpdateTradeExecutionCommand
    {
       public string Script()
        {
            return @"
            UPDATE [TradingBE].[dbo].[TradeExecutions]
            SET [PositionId] = @PositionId,
                [symbol] = @Symbol,
                [securityID] = @SecurityID,
                [tradeID] = @TradeID,
                [dateTime] = @DateTime,
                [tradeDate] = @TradeDate,
                [quantity] = @Quantity,
                [tradePrice] = @TradePrice,
                [ibCommission] = @IbCommission,
                [ibCommissionCurrency] = @IbCommissionCurrency,
                [closePrice] = @ClosePrice,
                [cost] = @Cost,
                [fifoPnlRealized] = @FifoPnlRealized,
                [buySell] = @BuySell,
                [transactionID] = @TransactionID,
                [ibExecID] = @IbExecID,
                [brokerageOrderID] = @BrokerageOrderID,
                [exchOrderId] = @ExchOrderId,
                [extExecID] = @ExtExecID,
                [orderType] = @OrderType,
                [traderID] = @TraderID,
                [currency] = @Currency,
                [description] = @Description,
                [conid] = @Conid,
                [taxes] = @Taxes,
                [assetCategory] = @AssetCategory,
                [expiry] = @Expiry,
                [transactionType] = @TransactionType,
                [exchange] = @Exchange,
                [proceeds] = @Proceeds,
                [netCash] = @NetCash,
                [mtmPnl] = @MtmPnl,
                [origTradePrice] = @OrigTradePrice,
                [origTradeDate] = @OrigTradeDate,
                [origTradeID] = @OrigTradeID,
                [origOrderID] = @OrigOrderID,
                [origTransactionID] = @OrigTransactionID,
                [ibOrderID] = @IbOrderID,
                [openDateTime] = @OpenDateTime,
                [initialInvestment] = @InitialInvestment,
                [accountId] = @AccountId,
                [acctAlias] = @AcctAlias,
                [model] = @Model,
                [fxRateToBase] = @FxRateToBase,
                [subCategory] = @SubCategory,
                [securityIDType] = @SecurityIDType,
                [cusip] = @Cusip,
                [isin] = @Isin,
                [figi] = @Figi,
                [listingExchange] = @ListingExchange,
                [underlyingConid] = @UnderlyingConid,
                [underlyingSymbol] = @UnderlyingSymbol,
                [underlyingSecurityID] = @UnderlyingSecurityID,
                [underlyingListingExchange] = @UnderlyingListingExchange,
                [issuer] = @Issuer,
                [issuerCountryCode] = @IssuerCountryCode,
                [multiplier] = @Multiplier,
                [relatedTradeID] = @RelatedTradeID,
                [strike] = @Strike,
                [reportDate] = @ReportDate,
                [putCall] = @PutCall,
                [principalAdjustFactor] = @PrincipalAdjustFactor,
                [settleDateTarget] = @SettleDateTarget,
                [tradeMoney] = @TradeMoney,
                [openCloseIndicator] = @OpenCloseIndicator,
                [notes] = @Notes,
                [clearingFirmID] = @ClearingFirmID,
                [relatedTransactionID] = @RelatedTransactionID,
                [rtn] = @Rtn,
                [orderReference] = @OrderReference,
                [volatilityOrderLink] = @VolatilityOrderLink,
                [orderTime] = @OrderTime,
                [holdingPeriodDateTime] = @HoldingPeriodDateTime,
                [whenRealized] = @WhenRealized,
                [whenReopened] = @WhenReopened,
                [levelOfDetail] = @LevelOfDetail,
                [changeInPrice] = @ChangeInPrice,
                [changeInQuantity] = @ChangeInQuantity,
                [isAPIOrder] = @IsAPIOrder,
                [accruedInt] = @AccruedInt,
                [positionActionID] = @PositionActionID,
                [serialNumber] = @SerialNumber,
                [deliveryType] = @DeliveryType,
                [commodityType] = @CommodityType,
                [fineness] = @Fineness,
                [weight] = @Weight
            WHERE [Id] = @Id";
        }
    }
}
